Made progress on bootstrap project
mockito/shipkit-bootstrap pull request #7
Opened 2017-08-20 05:35 UTC by szczepiq

It's coming along! Bootstrap project is fundamental for documentation and promotion.

- bumped shipkit and improved comments in the build.file so that it's easier to understand
- updated configuration, remove unnecessary stuff, improved logging so that users will see useful info
- updated travis config for latest shipkit, added some missing travis configuration so that Travis is faster
- described thoroughly the Shipkit test drive scenario in readme file, refreshed readme

2017-08-20 13:40 UTC, szczepiq commented
Friendly ping!

2017-08-20 13:59 UTC, wwilk requested changes
Just a small change, thanks for updating it!

2017-08-20 13:59 UTC, wwilk commented on README.md
> +Upstream repo is no good because you don't have permissions and you cannot merge immediately.
This parameter in pull request is called "base" not "base fork"

2017-08-21 00:38 UTC, szczepiq commented on README.md
> +Upstream repo is no good because you don't have permissions and you cannot merge immediately.
In GitHub Web UI it's called "base fork" or "base repository". This instruction step is for using GitHub Web and I will accompany it with a sweet screenshot :)

I'm moving on merging if that's ok, we can discuss / update the naming in the next PR.

2017-08-21 00:38 UTC, merged